set -l hc "\#000000 \#FFFFFF \#FF0000 \#00FF00 \#0000FF \#FFFF00 \#FF00FF \#00FFFF"

complete -c hellwal -f
complete -c hellwal -rF -s i -l image -d "Set image file"
complete -c hellwal -f -s d -l dark -d "Set dark mode (default)"
complete -c hellwal -f -s l -l light -d "Set light mode"
complete -c hellwal -f -s c -l color -d "Enable colorized mode (experimental)"
complete -c hellwal -f -s v -l invert -d "Invert colors in the palette"
complete -c hellwal -f -s m -l neon-mode -d "Enhance colors for a neon effect"
complete -c hellwal -f -s r -l random -d "Pick random image or theme"
complete -c hellwal -f -s q -l quiet -d "Suppress output"
complete -c hellwal -f -s j -l json -d "Prints colors to stdout in json format, it's skipping templates"
complete -c hellwal -rF -s s -l script -d "Execute script after running hellwal"
complete -c hellwal -x -s f -l template-folder -a "(__fish_complete_directories)" -d "Set folder containing templates"
complete -c hellwal -x -s o -l output -a "(__fish_complete_directories)" -d "Set output folder for generated templates"
complete -c hellwal -rF -s t -l theme -d "Set theme file or name"
complete -c hellwal -x -s k -l theme-folder -a "(__fish_complete_directories)" -d "Set folder containing themes"
complete -c hellwal -x -s g -l gray-scale -a "(seq 0 .1 1)" -d "Apply grayscale filter"
complete -c hellwal -x -s n -l dark-offset -a "(seq 0 .1 1)" -d "Adjust darkness offset"
complete -c hellwal -x -s b -l bright-offset -a "(seq 0 .1 1)" -d "Adjust brightness offset"
complete -c hellwal -f -l check-contrast -d "Ensure colors are readable against the background"
complete -c hellwal -f -l preview -d "Preview current terminal colorscheme"
complete -c hellwal -f -l preview-small -d "Preview current terminal colorscheme - small factor"
complete -c hellwal -f -l debug -d "Enable debug mode"
complete -c hellwal -f -l version -d "Print version and exit"
complete -c hellwal -f -l no-cache -d "Disable caching"
complete -c hellwal -f -l skip-term-colors -d "Skip setting colors to the terminal"
complete -c hellwal -f -l skip-luminance-sort -d "Skip sorting colors before applying"
complete -c hellwal -x -l static-background -a $hc -d "Set static background color"
complete -c hellwal -x -l static-foreground -a $hc -d "Set static foreground color"
complete -c hellwal -f -s h -l help -d "Display this help and exit"
